context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "RNNoise Mic"
      media.name = "RNNoise Mic"

      filter.graph = {
        nodes = [
          {
            type = ladspa
            name = rnnoise
            plugin = /usr/lib/ladspa/librnnoise_ladspa.so
            label = noise_suppressor_mono
            control = {
              "VAD Threshold (%)" = 50.0
              "VAD Grace Period (ms)" = 200
              "Retroactive Grace (ms)" = 0
            }
          }
        ]
      }

      capture.props = {
        node.name = "capture.rnnoise_mic"
        media.class = "Audio/Sink"
      }

      playback.props = {
        node.name = "rnnoise_mic"
        media.class = "Audio/Source"
      }
    }
  }
]
